# Generated by Django 6.0.5 on 2026-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_pass_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='interview_pass_app.skill'),
        ),
    ]
